var default = Handlebars.template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
  var stack1, helper, functionType="function", helperMissing=helpers.helperMissing, escapeExpression=this.escapeExpression, buffer = "﻿<!DOCTYPE html>\r\n<html lang=\"es\">\r\n<head>\r\n    <meta charset=\"utf-8\">\r\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n\r\n    <title>"
    + escapeExpression(((helper = (helper = helpers.meta_title || (depth0 != null ? depth0.meta_title : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"meta_title","hash":{},"data":data}) : helper)))
    + "</title>\r\n    <meta name=\"description\" content=\""
    + escapeExpression(((helper = (helper = helpers.meta_description || (depth0 != null ? depth0.meta_description : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"meta_description","hash":{},"data":data}) : helper)))
    + "\" />\r\n    <meta name=\"google-site-verification\" content=\"N9BewCljjj1CcRaE1gDkxtHPrEwXD_TrJJS9ubfLsz4\" />\r\n    <meta name=\"HandheldFriendly\" content=\"True\" />\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n    <link rel=\"shortcut icon\" href=\""
    + escapeExpression(((helpers.asset || (depth0 && depth0.asset) || helperMissing).call(depth0, "favicon.ico", {"name":"asset","hash":{},"data":data})))
    + "\">\r\n\r\n    <link href=\""
    + escapeExpression(((helpers.asset || (depth0 && depth0.asset) || helperMissing).call(depth0, "css/all.css", {"name":"asset","hash":{},"data":data})))
    + "\" rel=\"stylesheet\">\r\n    <link href='http://fonts.googleapis.com/css?family=Courgette|Lato:400,700' rel='stylesheet' type='text/css'>\r\n\r\n    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n    <!--[if lt IE 9]>\r\n      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n    <![endif]-->\r\n    "
    + escapeExpression(((helper = (helper = helpers.ghost_head || (depth0 != null ? depth0.ghost_head : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"ghost_head","hash":{},"data":data}) : helper)))
    + "\r\n</head>\r\n\r\n<body class=\""
    + escapeExpression(((helper = (helper = helpers.body_class || (depth0 != null ? depth0.body_class : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"body_class","hash":{},"data":data}) : helper)))
    + "\">\r\n    ";
  stack1 = ((helper = (helper = helpers.body || (depth0 != null ? depth0.body : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"body","hash":{},"data":data}) : helper));
  if (stack1 != null) { buffer += stack1; }
  return buffer + "\r\n    "
    + escapeExpression(((helper = (helper = helpers.ghost_foot || (depth0 != null ? depth0.ghost_foot : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"ghost_foot","hash":{},"data":data}) : helper)))
    + "\r\n\r\n    <script src=\""
    + escapeExpression(((helpers.asset || (depth0 && depth0.asset) || helperMissing).call(depth0, "js/custom.js", {"name":"asset","hash":{},"data":data})))
    + "\"></script>\r\n    <!-- Custom Scripts -->\r\n    <script>\r\n        $(document).ready(function () {\r\n            $('.post-content img[alt]').each(function () {\r\n                $(this).wrap('<a target=\"_blank\" href=\"' + this.src + '\" class=\"thumbnail\"></a>');\r\n                $('<p class=\"text-center\">' + this.alt + '</p>').insertAfter(this);\r\n\r\n                var theImage = new Image();\r\n                theImage.src = $(this).attr(\"src\");\r\n                var original = $(this);\r\n\r\n                $(theImage).load(function () {\r\n                    if (this.height > this.width) $(original).css(\"width\", \"30%\");\r\n                });\r\n            });\r\n\r\n            if ($('#instafeed').length > 0) {\r\n                new Instafeed({\r\n                    get: 'user',\r\n                    userId: 1591756528,\r\n                    limit: 7,\r\n                    accessToken: '1591756528.467ede5.7469a2fdbbdf463ebb9ec7f8ca79c1d3',\r\n                    resolution: 'low_resolution'\r\n                }).run();\r\n            }\r\n        });\r\n\r\n        (function () {\r\n            var css = document.createElement('link');\r\n            css.href = '//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css';\r\n            css.rel = 'stylesheet';\r\n            css.type = 'text/css';\r\n            document.getElementsByTagName('head')[0].appendChild(css);\r\n        })();\r\n\r\n        (function (i, s, o, g, r, a, m) {\r\n            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {\r\n                (i[r].q = i[r].q || []).push(arguments)\r\n            }, i[r].l = 1 * new Date(); a = s.createElement(o),\r\n            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)\r\n        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');\r\n\r\n        ga('create', 'UA-132920-17', 'auto');\r\n        ga('send', 'pageview');\r\n    </script>\r\n</body>\r\n</html>";
},"useData":true});